name: Update Version in __init__.py

on:
  workflow_call:
    inputs:
      package_path:
        description: 'Path to the package directory containing __init__.py'
        required: true
        type: string

permissions:
  contents: write

jobs:
  update-version-in-init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          VERSION=${TAG_NAME#v}
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Get current version from __init__.py
        id: get_current_version
        run: |
          CURRENT_VERSION=$(grep -oP '__version__ = "\K[^"]+' "${{ github.event.repository.name }}/__init__.py")
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Check if new version is larger than current version
        id: check_tags
        run: |
          # Compare the versions using shell sorting for semantic versioning
          NEW_VERSION="${{ env.version }}"
          CURRENT_VERSION="${{ env.current_version }}"
          
          echo "Current Version:  $CURRENT_VERSION"
          echo "New Version:      $NEW_VERSION"

          if [[ "$(printf '%s\n' "$NEW_VERSION" "$CURRENT_VERSION" | sort -V | tail -n 1)" != "$NEW_VERSION" ]]; then
            echo "Error: Version ${{ env.version }} is not larger than the current version in __init__.py"
            exit 1
          fi

      - name: Update __init__.py with new version
        run: |
          sed -i "s/__version__ = \".*\"/__version__ = \"${{ env.version }}\"/g" "${{ github.event.repository.name }}/__init__.py"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@centura.ch"
          git add "${{ github.event.repository.name }}/__init__.py"
          git commit -m "chore: update __version__ to ${{ env.version }}"
          git push origin main
